# Generated by Django 4.2 on 2026-02-17 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='school_class',
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='jshshr',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='JSHSHR 14 ta raqamdan iborat bo‘lishi kerak.', regex='^\\d{14}$')]),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='passport_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Passport formati: 2 ta katta harf + 7 ta raqam (masalan: AB1234567).', regex='^[A-Z]{2}\\d{7}$')]),
        ),
    ]
