# Generated by Django 4.2 on 2026-03-03 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MON', 'Dushanba'), ('TUE', 'Seshanba'), ('WED', 'Chorshanba'), ('THU', 'Payshanba'), ('FRI', 'Juma'), ('SAT', 'Shanba')], max_length=3, verbose_name='Hafta kuni')),
                ('lesson_order', models.PositiveIntegerField(verbose_name='Dars tartib raqami')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('room', models.CharField(blank=True, max_length=100, null=True, verbose_name='Xona')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academic.classsubject', verbose_name='Sinf-Fan-O‘qituvchi')),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
                'ordering': ['weekday', 'lesson_order', 'start_time'],
                'unique_together': {('class_subject', 'weekday', 'lesson_order')},
            },
        ),
    ]
