# Generated by Django 4.2 on 2026-03-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='weekday',
            field=models.CharField(choices=[('MON', 'Dushanba'), ('TUE', 'Seshanba'), ('WED', 'Chorshanba'), ('THU', 'Payshanba'), ('FRI', 'Juma')], max_length=3, verbose_name='Hafta kuni'),
        ),
    ]
