# Generated by Django 4.2 on 2026-04-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_must_change_password'),
        ('academic', '0004_alter_timetable_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('current', 'Joriy baho'), ('midterm', 'Oraliq baho'), ('final', 'Yakuniy baho')], default='current', max_length=10, verbose_name='Baho turi')),
                ('value', models.PositiveSmallIntegerField(verbose_name='Baho (1-5)')),
                ('date', models.DateField(verbose_name='Sana')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic.classsubject', verbose_name='Sinf-Fan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.studentprofile', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Baho',
                'verbose_name_plural': 'Baholar',
                'ordering': ['-date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('absent', 'Kelmadi'), ('late', 'Kech keldi')], default='present', max_length=10, verbose_name='Holat')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academic.classsubject', verbose_name='Sinf-Fan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.studentprofile', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomatlar',
                'ordering': ['-date', 'student'],
                'unique_together': {('class_subject', 'student', 'date')},
            },
        ),
    ]
